# Generated by Django 3.2.7 on 2021-11-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_code', models.CharField(max_length=7, unique=True)),
                ('module_name', models.CharField(max_length=255)),
                ('level', models.IntegerField(max_length=1)),
                ('credits', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('programme', models.CharField(max_length=255)),
                ('year_of_study', models.IntegerField(max_length=1)),
                ('student_number', models.CharField(max_length=9, unique=True)),
                ('modules_studying', models.ManyToManyField(to='main.Module')),
            ],
        ),
    ]
